var car={
    type:'hypercar',
    maxRpm:19700,
    idle:3000,
    audio:'https://cdn.jsdelivr.net/gh/freemediaengineer/game@main/grit%20hyperdrive.wav',
     topSpeed:200,
        gears:[80,19,15,14,10,8,7,6,5,4,3,3,2,2,1],
        accelScore:0,
        doors:2,
        door1:{
         color:'red',
            length:50,
        },
        door2:{
            color:'red',
            length:50
        },
        hood:{
            color:'red',
            length:20
        },
        trunk:{
            color:'red',
            length:20
        },
        top:{
            length:100,
            x:20,
            y:50
        }
}